### ISSUE TITLE
Timezone doesn't match to my local time.

### ISSUE THREAD

**Issue by frailbongat** [Ivy-Apps/ivy-wallet#1200]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

My current local date was August 10, 2022 but in ivy it's August 9, 2022.

### To Reproduce

1. Set your time to GMT+8 to match my local time. And log data to ivy. You should be able to see time difference.

### Expected behavior

Ivy date and time will match local date and time for logged user

### Smartphone

Blackshark 4

**Comment by rezakelidari** [comment]
I also have the same problem, but taking into account the daylight savings time, the problem is solved for me.

I live in Tehran and our time is +03:30 GMT, but it changes to +04:30 in the summer, so if I want to enter a time outside of summer, the time I enter and the time it is recorded are one hour apart. Also, if I enter the time, for example, 23:30, it will be converted to 00:30 the next day.
