### ISSUE TITLE
To manually adjust currency rates, as some official currency rates don't reflect real rates.

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1295]

**Comment by gerapicon** [comment]
Also, adjust currency rates per transaction would be great. Here in argentina the rate fluctuates pretty quickly.

**Comment by Pkcarreno** [comment]
Hey @gerapicon, I think the same thing, I am from Venezuela and something similar happens.

I think it is a matter of how we use the app and I was thinking of some suggestions to correct that. Could you confirm me if your main currency is other different than your country's currency?

In my case, I have the app configured to USD although the currency of my country is VES and when making transactions between accounts is complicated to make the calculation and also inaccurate, because the calculation operation is based on how much is equivalent to 1 unit of the target currency in USD (currency set in the app by me). And usually the exchange operations (this is my case, I don't know if it is different in other countries) it shows how much a unit of the target currency (example: USD) is worth in my local currency (example: VES), then to make the calculation I have to divide that number by 1. example:

My local currency is worth 8 VES per USD.
Then I have to do 1 / 8 which gives me 0.125 USD per VES, that is the amount I have to put to do the operation.

But when the value of the currency is not exact and has some decimal (example: 8.09 VES per USD) the calculation becomes imprecise due to the limitation of having 4 digits after the comma.

![1663192817336 (1)](https://user-images.githubusercontent.com/34664891/190270943-7da8aef8-887f-4a57-8c1c-aa0ba811cb1c.jpg)



I had previously created a request on this topic [#1004](https://github.com/Ivy-Apps/ivy-wallet/issues/1004)


I can think of 2 ways to solve this problem:
1. Switch between which is the base currency of the exchange rate: With a button next to the button where you reset the rate.
2. Set the exact amount to be obtained in the same way as the amount to be spent in the operation.



P.S.: due to inflation in my country, for me it is more comfortable to project my finances in a stable currency like the USD than in my local currency, that's why I have the app configured that way.

**Comment by code-a1** [comment]
#1004 Duplicate
