### ISSUE TITLE
Transacciones De Deudas Y Prestamos

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1626]

**Comment by Pkcarreno** [comment]
"Debt and Loan Transactions"

I think it refers to being able to make transfers between accounts but to mark it as a loan instead of having the money directly in the account.
I usually register the transfers and then create the loan in the loan section, so it would be an interesting shortcut

Otherwise I don't know what he is referring to since the loan section already exists.
