### ISSUE TITLE
Please add IRT Currency 

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#1856]
Iranian tomans
تومان

**Comment by eiliatmr** [comment]
Hi. It seems there is no IRT in the list and the first guy who mentioned it didnt fully explain what is missing.

Iranian Toman(IRT) is different from Iranian Rial.
Iranian Toman has one less 0 compare to IRR.

e.g
12,000 rial = 1,200 toman.

Please add IRT currency because its getting used by the majority of the people here compare to IRR
