### ISSUE TITLE
Add start and end dates for the budgets. Not everything is monthly

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#2176]

**Comment by matthewjdewhurst** [comment]
I noticed this not long after posting about being able to save custom date ranges (#2187) as this follows a similar vein.

It's worth mentioning that this is also the case on the 'Categories' view. I think **both** the 'Budgets' and 'Categories' views should reflect the custom range currently set by the user.

### Use Case

I'll use my use case from #2187 again as an example - my personal preference when viewing my finances is to see what's come in and gone out from the day I get paid to the day before I'm next due to get paid. Using the current month as template, this would be April 28th - May 30th.

### The Categories View

When I view 'Categories' for example, my "Household Bills" is reporting as £0.00 because I entered all the expenses for this category on the day I got paid, which was April 28th and not covered by the default date range on this view.

### The Budgets View

Similarly, on the 'Budgets' view, the left to spend is reporting incorrectly based on the custom date range I have set. For example, my "Work Dinners" category which has a budget of £20 is reporting I have £14.80 left to spend, which in actual fact I've spent £8.45, and I have £11.55 left to spend. This again is because any expenses against the "Work Dinners" category that reside outside the default dates (which display as April 30th - May 31st for the current month) are not included.

Hope this insight helps. 👍🏼
