### ISSUE TITLE
Compact Layout

### ISSUE THREAD

**Issue by ivywallet** [Ivy-Apps/ivy-wallet#2475]
Can you create a compact layout? Because the current layout looks too big in my phone screen

**Comment by pedy** [comment]
Thanks for this great and fancy software 👌🏻
You closed this as 'completed' because it's already implemented?
Version 4.5.0 (150) looks this big on my Huawei Mate 10 (1440 x 2560 pixels, 16:9 ratio):
![Screenshot_20240328_150353_com ivy wallet](https://github.com/Ivy-Apps/ivy-wallet/assets/7770727/6799123e-010a-49ee-90ec-246dafd71c60)
![Screenshot_20240328_150415_com ivy wallet](https://github.com/Ivy-Apps/ivy-wallet/assets/7770727/828b4885-f12e-42e8-99aa-4833fdf1a996)

**Comment by ILIYANGERMANOV** [comment]
All @ivywallet issues were auto closes, it's not completed
