### ISSUE TITLE
Automate Issue Assigning to contributors

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [Ivy-Apps/ivy-wallet#2769]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Automate the process for assigning issues to contributors.

### Because...

- I'm too lazy and busy to do it manually.

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ivywallet** [comment]
⚠️ Hey @ILIYANGERMANOV, this issue is already taken by @ILIYANGERMANOV.
**Do not start working on it!**
Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ivywallet** [comment]
⚠️ Hey @ILIYANGERMANOV, this issue is already taken by @ILIYANGERMANOV.
**Do not start working on it!**
Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ivywallet** [comment]
⚠️ Hey @ILIYANGERMANOV, this issue is already taken by @ILIYANGERMANOV.
**Do not start working on it!**
Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ivywallet** [comment]
⚠️ Hey @ILIYANGERMANOV, this issue is already taken by @ILIYANGERMANOV.
**Do not start working on it!**
Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ivywallet** [comment]
⚠️ Hey @ILIYANGERMANOV, this issue is already taken by @ILIYANGERMANOV.
**Do not start working on it!**
Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
I'm on it!!

**Comment by ivywallet** [comment]
⚠️ Hey @ILIYANGERMANOV, this issue is already taken by @ILIYANGERMANOV.
**Do not start working on it!**
Please, [pick another one](https://github.com/Ivy-Apps/ivy-wallet/issues).

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by ILIYANGERMANOV** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @ILIYANGERMANOV! 🎉
Issue #2769 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please unassign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
