### ISSUE TITLE
[BUG] Unable to add categories during onboarding

### ISSUE THREAD

**Issue by theabhishekbhujang** [Ivy-Apps/ivy-wallet#3017]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Unable to add categories for the very first time the app is installed and launched in the latest alpha release.

### To Reproduce

1. Install the latest alpha release.
2. Set up the basics like your currency etc.
3. Now, try adding categories and you should be able to reproduce the issue

### Smartphone

Redmi Note 5 Pro (whyred); Android: 9 (pie)

**Comment by ILIYANGERMANOV** [comment]
I suppose this happens only in the onboarding flow?

**Comment by theabhishekbhujang** [comment]
yes

**Comment by isaacnguyen0809** [comment]
I'm on it

**Comment by ivywallet** [comment]
Thank you for your interest @isaacnguyen0809! 🎉
Issue #3017 is assigned to you. You can work on it! ✅

_If you don't want to work on it now, please un-assign yourself so other contributors can take it._

Also, make sure to read our [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).

**Comment by isaacnguyen0809** [comment]
Hi @ILIYANGERMANOV, when I investigate the error of this issue, I found out that it is because we lack Annotation Singleton for CategoryRepositoryImpl, so every time CategoryRepositoryImpl is created, it will create new categoriesMemo that affects the caching of categories. And luckily, when I pulled the latest code, @diasmashikov already fixed the problem. So I think we can close this ticket.
