### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by miqdad19** [Ivy-Apps/ivy-wallet#3404]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

Need a wallet

### Because...

Karena jika didalam satu akun terdapat beberapa wallet
Itu lebih memudahkan

### Description

Karena orang mempunyai beberapa tujuan di dalam satu akun

Kita membutuhkan improvisasi seperti itu

**Comment by ivywallet** [comment]
Thank you @miqdad19 for raising Issue #3404! 🚀
What's next? Read our **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) 📚**.

_Tagging @ILIYANGERMANOV for review & approval 👀_

**Comment by dinesh-58** [comment]
Translation from Indonesian:

Because if there are several wallets in one account, it makes things easier.
Because people have multiple goals in one account
We need such improvisation

I'm assuming they mean having multiple saving goals in the app. Can be considered duplicate of #2785 since that's the only similar issue that's still open.
